### PR TITLE
Credits extension to include Submitter & Translator

### PR DESCRIPTION
**Pull request by abhiprojectz**
This fixes: [#358 ](https://github.com/sawaliram/sawaliram/issues/358)

### CODE REVIEW

**Review by Sshashank18 — CHANGES_REQUESTED** [review]
It shows credits on view answer and view article page. But the issue mentions that the credit section should be added to Translate Content also.

**Comment by abhiprojectz** [comment]
> It shows credits on view answer and view article page. But the issue mentions that the credit section should be added to Translate Content also.

It means that if a published answer/article has a translation then the credits needs to be given to them also like below:
hghg

**Review by Sshashank18 — APPROVED** [review]
if that's the case, then it is working fine

**Comment by jr-sawaliram** [comment]
#358 is reopened as Translator credit is still to be added. This PR is taking the Submitter to be the Translator.

**Pull request merged**
