### PR TITLE
Adds image upload functionality to ckeditor

### LINKED ISSUE #415: Specify maximum image size for articles and answers
Large images slow down the editor. 200 KB maximum size should be mandated.

### PR DESCRIPTION
**Pull request by abhiprojectz**
Fixes #415 

For more details refers to #415

### CODE REVIEW

**Review by badrihippo — APPROVED** [review]
Looking good from my end; of course someone else should test and see that it actually works!

**Comment by jr-sawaliram** [comment]
@Abirami8799 @Thenmozhi295 can you test this PR? @badrihippo please see.

**Comment by badrihippo** [comment]
Conflicts are simple to resolve; just delete lines 238, 241, and 258 (as of now).

Maybe @Abirami8799 can run this and see if it works since she is more ahead in terms of code right now? Basically after this PR, when adding images, the images should be uploaded to a separate media directory (instead of being inline as base64 like now).

**Review by Abirami8799 — APPROVED** [review]
Working fine

**Pull request merged**
