### PR TITLE
Translation page redesign and styling

### LINKED ISSUE #216: Comments section should display below content in mobile view
Right now, the comments try to show on the side of the page even in the mobile view, making for really thin columns that are hard to work with :grimacing:

### LINKED ISSUE #217: Translation pages do not follow the new design
The current translation pages are largely unstyled. They should be updated to use the designs provided by Pragnya, as in the below screenshot:

Group 2798

Additionally, the intermediate "select language to translate from/to" page should ideally be omitted.

### PR DESCRIPTION
**Pull request by badrihippo**
Add styling to translation pages to make them fit the new design.

- [x] Base Edit Translation page
- [x] Edit Article Translation
- [x] Edit Answer Translation

Also, make the following internal updates
- [x] Make static content of translation templates translatable
- [x] Bugfix: display the "category" filter in the translation list page

Fixes #217, and also happens to fix #216.

### CODE REVIEW

**Comment by badrihippo** [comment]
I've finished styling both the translation pages. The article one follows Pragnya's design except for the extra buttons which don't have an implementation yet (probably should be in a separate issue). The answer version has a temporary design based on articles; I'll update it once the design screens from Pragnya come in.

@nitinpaul you can either merge it in now and create a separate issue when the answer page design comes in, or leave this open until then and merge them all at once.

**Comment by badrihippo** [comment]
This seems to have magically fixed #216 too :tada:

**Comment by badrihippo** [comment]
Looks like this magically fixes #224 as well :tada:

@nitinpaul can you link the issue (using the sidebar on the right)? I don't think I have the permissions to do it.

**Comment by nitinpaul** [comment]
I think it's best to leave this one open until the other bits are in place, just to be consistent with the UI and the process. A few things I noticed:
1. The 'category' filter is missing from the main translation page. 
2. We can drop the interstitial page where we select the languages etc, as discussed.
3. The actual translation interface that Pragnya designed looks good. The only problem I found was that the top button to select the languages doesn't seem clickable. I think we can keep the dropdown arrows next to the language name to make it more intuitive that it is a dropdown list

**Comment by badrihippo** [comment]
(2) is not related to styling. Let's make a separate issue.
I'll get to (1) and (2) when I'm done with search.

**Comment by badrihippo** [comment]
@nitinpaul (1) and (3) are now fixed, and I've also updated it to the new style by Pragnya.

One problem: I couldn't make the input grow when more text is entered. The only way to do this seems to be using `contenteditable=True`, and programmatically adding the text to the inputs later. Should we go for that, or let it be for now (because people probably won't type such long stuff anyway)?

(2) will be done in a separate commit, as I said earlier. We can do it once the new designs come in.

**Pull request merged**
