### PR TITLE
Compressor to minify static files

### LINKED ISSUE #428: Minification of static files  should be setup
Currently, The static files such as `CSS` , `JS` including `html` content are not (served) minified. A `compressor` should be a good choice, as it will reduce the page load time.

### PR DESCRIPTION
**Pull request by abhiprojectz**
Fixes #428

First install all requirements pip install -r requirements.txt

Then to compress run python manage.py compress on server

And in local run python manage.py compress --force

### CODE REVIEW

**Review by badrihippo — CHANGES_REQUESTED** [review]
Nice work. Can you add the compression instructions to the README so they don't get lost? (More or less what you wrote in the commit message; maybe format it a bit better or ask @jr-sawaliram to review before saving.

Also give an explanation of why `--force` is necessary for local development (I'm guessing that `compress` normally doesn't do any compression on dev environments to make debugging easier, and the `--force` is to override that. If that's the case you can write that or give some other explanation in the README).

**Comment by abhiprojectz** [comment]
@badrihippo  you are right by default the compressor don't compress in development environment. 

Alternatively , there is a variable to deal [this ](https://django-compressor.readthedocs.io/en/stable/settings/#django.conf.settings.COMPRESS_OFFLINE)  that is **COMPRESS_OFFLINE** which by default sets to false so , i have made that work in development environment and also added the instructions in Readme.

**Comment by abhiprojectz** [comment]
@badrihippo  yes you are right, made the changes.

**Review by badrihippo — APPROVED** [review]
Yup, looking good now! :+1:

**Review by subindevs — APPROVED** [review]

**Pull request merged**
