### PR TITLE
added page error500

### PR DESCRIPTION
**Pull request by subindevs**
made changes similar to the error 404

### CODE REVIEW

**Comment by nitinpaul** [comment]
Fix the title of the new page. It should be something like 'Internal Server Error'

**Comment by nitinpaul** [comment]
Is this tested? Set DEBUG=False in settings.py and generate a server error like so:  
```return HttpResponse(status=500)```

**Comment by nitinpaul** [comment]
Couple of things to check before merging:
- Remove the test code from settings.py and uncomment the original line of code
- Is it necessary to add the same code to dashboard/urls.py? Why isn't it necessary to do the same for the 404 handler?

**Comment by subindevs** [comment]
it's not necessary to add url to dashboard/urls.py . I have removed that and test code from the settings.py

**Comment by nitinpaul** [comment]
Two more things to fix before we merge:  
1. There's a stray import in the ```dasboard/urls.py``` file (```from django.conf.urls import handler500```)
2. Now that this PR has 4 commits, it's recommended to squash the commits together. Take a look at [this page](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) to learn more. The command you are looking for is:
```
$ git rebase -i HEAD~4
```

**Comment by badrihippo** [comment]
@nitinpaul can this be marked closed?

**Pull request closed without merging**
