### PR TITLE
Implement log generation

### LINKED ISSUE #13: No logs are generated/stored
Add or enable a robust logging system for the project. Logs are a critical component of any hosted platform and we cannot go into production without some form of logging enabled. Before setting up a logging system, please discuss the options.

### PR DESCRIPTION
**Pull request by badrihippo**
Fixes #13. You will need to create a `logs` subdirectory in the sawaliram root folder for this to work.

### CODE REVIEW

**Comment by nitinpaul** [comment]
Few points I've been thinking about:  
* The ideal setup would be one where all errors and warnings are sent to Sentry by the Django error handler, instead of us manually logging errors and warnings like ```logger.warning('404 error for %s', request.path)```. For a 404 error, for example, we might need to look at the stack trace, current variables set (if any) or some configuration details to debug the issue. 
* We might not need log entries for user login and logout. We could log user actions (like submitting questions), and attach the current user. 
* For submitting questions specifically, we don't need to log it since we will create a notification for admins whenever a user submits questions. We will probably store these kind of notifications in a table, which makes logging them redundant. 

To-Do:
* I will set up Sentry for the project and share the details. Please complete any configurations.
* Remove the ```logger.info``` type of lines, for now. 
* Setup Django to send all errors and warnings from the error handler to Sentry 
* Squash the multiple commits into one. Read more about it [here](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History). The command you're looking for is ```$ git rebase -i HEAD~3``` (for squashing last 3 commits)

**Comment by badrihippo** [comment]
Sounds good. A few points for clarification:

> * The ideal setup would be one where all errors and warnings are sent to Sentry by the Django error handler, instead of us manually logging errors and warnings like logger.warning('404 error for %s', request.path).

I'll look into it and see if we can do logging that way instead. Django already has a way to automatically log critical errors and I think the default behaviour is to try and send an email to the admin ID. We could change it from there to go to Sentry instead (when it's ready).

> * Remove the logger.info type of lines, for now.

Would you like to keep them as `logger.debug` instead? Might be useful while developing, to keep track of what's actually happening. It'd also be useful to have easily triggered log entries, at least until the system is properly set up.

> For submitting questions specifically, we don't need to log it since we will create a notification for admins whenever a user submits questions. We will probably store these kind of notifications in a table, which makes logging them redundant.

What if a person tries to submit a question but runs into some error? Does it make sense to keep logs in case that happens, or will we be able to sort it out by other means (eg. 500 reports)?

**Comment by nitinpaul** [comment]
> Would you like to keep them as logger.debug instead? Might be useful while developing, to keep track of what's actually happening. It'd also be useful to have easily triggered log entries, at least until the system is properly set up.

There is a limit of 5000 error messages per month on Sentry. Although I do remember reading somewhere in their documentation that manual logs of some type don't count. I'll verify this.

> What if a person tries to submit a question but runs into some error? Does it make sense to keep logs in case that happens, or will we be able to sort it out by other means (eg. 500 reports)?

These kind of errors will be caught by Sentry, so no need to log a failed operation manually on our part. Sentry would show a lot of useful information in our PHP/Laravel setup. Hopefully a python/Django setup is similar.

**Comment by badrihippo** [comment]
> There is a limit of 5000 error messages per month on Sentry. Although I do remember reading somewhere in their documentation that manual logs of some type don't count. I'll verify this.

Quick question: are we planning to do *all* logs on Sentry then? As opposed to having some as local logfiles, etc.? (I can remove the `.info` messages anyway; just wanted to clarify this point).

**Comment by badrihippo** [comment]
I think the setup is basically done, except for Sentry.

System errors like 404 and 500 get redirected to the dummy `'sentry'` handler I've created, which we can replace with the real one when its ready. As of now, the handler simply saves such messages to the `logs/sentry.log` files instead of `logs/sawaliram.log`.

The current setup uses the default handler for all log entries (`INFO` and up), while only the critical errors (`WARNING` and `ERROR`) make their way to Sentry. This can be changed with one line of code; we can fine-tune it later when we start writing logging entries and have a clearer picture of what kinds of events we want to keep track of.

@nitinpaul let me know when the Sentry details are out so I can implement them.

**Comment by badrihippo** [comment]
@nitinpaul closing this since Sentry has already been set up elsewhere. We can reopen later if required.

**Pull request closed without merging**
