### PR TITLE
Links on 'get involved' working

### LINKED ISSUE #386: Links on 'Get Involved' page are not working
Dashboard and GitHub links on 'Get Involved' page are not working.

### PR DESCRIPTION
**Pull request by Sshashank18**
This fixes #386

### CODE REVIEW

**Comment by abhiprojectz** [comment]
@Sshashank18 Please Follows these:
1. `git checkout -f links-getInvolved`
2. `git status`

The modified files will be marked with red color,
remove all unwanted changes except this (public_website/templates/public_website/get-involved.html) that is changes in scope of this PR. 

For removing unwanted files, just do this `git restore dashboard/views.py` + all other unwanted files, and commit the changes.

**Comment by abhiprojectz** [comment]
Just follow these same steps for [#391 ](https://github.com/sawaliram/sawaliram/pull/391) and  [#383 ](https://github.com/sawaliram/sawaliram/pull/383)

**Comment by jr-sawaliram** [comment]
@abhiprojectz @ukey54 please test one more time.

**Comment by ukey54** [comment]
Links are working now.
👍

**Comment by abhiprojectz** [comment]
working fine

**Pull request merged**
