### PR TITLE
Filters and Design Changes of Analytics Page

### PR DESCRIPTION
**Pull request by hitarths**
I have changed the design of the analytics page. If the button like design choice for filters is okay, then we can go ahead with a few more filters like this.

### CODE REVIEW

**Comment by nitinpaul** [comment]
Hi Hitarth! Thanks for the PR! Few things I noticed:
1. The analytics styles seem to be changing the styles of all buttons - including in the header and the footer. Also adds a shadow to the header.
2. The 'Gender Split' button only works once, after clicking it once it doesn't let you change back.
3. The includes for bootstrap, fontawesome, google font etc are already present in the base template inherited by every page.
4. What is `bootstrap-multiselect.js` being used for?
5. It appears that `touchswipe.js` is only used to add horizontal scroll for the graphs. I think it might be possible to do it with CSS
6. Some styling inconsistencies - using both full-width and container-width `<hr>`'s, uneven spacing in the donut graph section
7. The donut labels should be vertical aligned not wrapping. It looks odd because of the inconsistency.

**Comment by hitarths** [comment]
Hi Nitin,
I was really busy these days, sorry for the late reply.

1,2,3,6: Noted.
4. It is not being used in this PR, but I planned to use it in the other filters which will _multiple selections_. I'll remove it if I won't use it.
5. I don't want us to worry about the compatibility issues. Also, it is not a heavy library and its size is pretty small.
7. I did that after considerable thinking; the labels look, at least to me, odd if we stack them vertically. On a small screen phone, they take too much space than necessary. Try opening the previous version and this one on a mobile phone to observe the difference. Notice that hovering over/touching the sections of the doughnut also gives the information about that section.

- Hitarth

**Comment by nitinpaul** [comment]
> 5. I don't want us to worry about the compatibility issues.

Which compatibility issues are you referring to? 'touchswip.js' is useful when we need to catch touch or swipe 'events' and perform an action like slide a carousel or switch a tab, but is not required to add a horizontal scroll. Best to keep the code lean with minimal dependencies. 

7. The labels right now appear like this for me - for 3 labels they appear:
1 2
3
When it should either be:
1 2 3
or 
1
2
3
Isn't a vertical stack better for mobile where horizontal screen space is less? A quick change to the CSS and it looks fine on desktop too. Can you tell me what issues you faced with the labels?

**Comment by hitarths** [comment]
Hi Nitin,
> It appears that touchswipe.js is only used to add horizontal scroll for the graphs.

> Which compatibility issues are you referring to? 'touchswip.js' is useful when we need to catch touch or swipe 'events' and perform an action like slide a carousel or switch a tab, but is not required to add a horizontal scroll. Best to keep the code lean with minimal dependencies.

I don't know what exactly you mean here by "horizontal scroll", but TouchSwipe is being used to detect swipe 'events' to dynamically change the title, filters available and the graph; see anayltics.js, line 180. If you want to write a JS function to detect "swipe" and "dragging the mouse while clicked" above a certain threshold, it won't be an issue for me to replace the touchswipe.js with that function. To avoid unnecessary complexity of the code, I prefer to use libraries unless they bring considerable performance issues.

> Isn't a vertical stack better for mobile where horizontal screen space is less? A quick change to the CSS and it looks fine on desktop too. Can you tell me what issues you faced with the labels?

It is more of a style choice, and hence these questions cannot have a single correct answer. There is no issue as such with vertical stack labels, I just didn't find it aesthetically pleasing. I am attaching a few pictures on Zulip for reference. I'll leave it to you and others to decide which one looks better.

Thanks,
Hit

**Comment by nitinpaul** [comment]
@hitarths Can you briefly explain what touchswip.js is being used for on this page?

**Comment by hitarths** [comment]
@nitinpaul In mobile phones, using radio buttons for selecting the graph was not a good choice. I replaced that with "swiping". You need to open the site on a mobile phone (or use Chrome's feature) to see it in action.

**Comment by nitinpaul** [comment]
I think this is not good UX for the user - a better way is to use a dropdown list at the top. It is much more simpler, intuitive and does not require an additional library. I'd wager even a simple carousel would work well, but the simplest design is a dropdown. Keeping the code simple and the list of dependencies short is key for the project!

**Pull request closed without merging**
