### PR TITLE
Analytics app added

### PR DESCRIPTION
**Pull request by hitarths**
Added the analytics app.

### CODE REVIEW

**Comment by nitinpaul** [comment]
Hello @hitarths! Thanks for the PR, looks like a lot of work has gone in. Few things to clarify and fix:
1. Is there a reason for this to be a separate app? The site is logically divided into Dashboard and Public Website and we are maintaining that in the code. The Analytics page should be a part of the public_website app. Is it possible to move the code into it?
2. The website styles are broken: 
Screenshot 2020-04-27 at 4 01 22 PM
3. The CSS and JS should be part of style.css and script.css, which are linked in the base.html template. It should avoid the styling problems. 
4. The `analytics/lang.py` should be useful elsewhere too, thanks for that! 😄 
5. The analytics page itself and graphs (especially the map of India) look really nice! It should be perfect with some small tweaks to make it consistent with the website design - like changing the orange-ish background on some of the components to #f2f2f2 
6. In analytics/templates/home.html, line #134 has some inline JS. Can they too be moved in with the other JS? Or are they needed to be there? (Asking for clarity)

Overall, very good PR Hitarth, thank you from Sawaliram :)

**Comment by hitarths** [comment]
Hi @nitinpaul,
1. I usually separate the stuff which I think doesn't interact much with rest; given the logical division of Sawliram, I don't think it will be an issue to put this with Public Website. I'll do that.

2. I started working on a while ago, on that version the styles were fine. I found out that there have been a lot of changes in the code recently, so I pulled the latest version yesterday and found out that the styles were broken. I didn't fix it cause there was some heavy change in the base.html.

3. The problem is not due to separate CSS and JS files. I don't think we should add these CSS and JS files with those of base.html as this is only used inside the analytics page. Also, the script tries to find the HTML elements (canvases, etc) to create the graphs. That will result in errors on the other pages (in WebConsole) if added to the other pages' JS.

5. I will change the colors :)

6. That part is required to pass the data to JS.

Thanks :)

**Comment by nitinpaul** [comment]
UPDATE: @hitarths looks like point #2 about the styling issue is not from this PR. We will look at it separately.

**Comment by nitinpaul** [comment]
Your points seem good. Agree on the separate JS and CSS 👍 
The new MASTER will have the fixed styles, we had to revert the last commit. Not sure what is causing the issue. Will investigate. Any pointers that might help are much appreciated :)

**Comment by hitarths** [comment]
Hi, I have updated the branch. I have added the tags for translations in the files.
@nitinpaul I didn't quite get where you wanted the color to be changed. But I am quite sure we can change that by modifying the CSS.
Thanks!

**Comment by nitinpaul** [comment]
This looks good @hitarths! Thank you! 
We'll make some incremental changes, like fleshing out the text and possibly making some design changes, once our designer friend Rohit has a look. Would you be up for making some of those changes? It's not going to have hard deadlines :)

Thanks again for the good work, this is a high quality PR!

**Pull request merged**
