### PR TITLE
Credits system for translated content in translation interface.

### PR DESCRIPTION
**Pull request by abhiprojectz**
**Description:**
This creates the credits system for translation interface.

Fixes [#358 ](https://github.com/sawaliram/sawaliram/issues/358)

**Info:**
While testing/pushing to server only migrate for **dashboard app** that is  `python manage.py migrate dashboard` .

### CODE REVIEW

**Review by Sshashank18 — APPROVED** [review]
Working fine on my localhost.

**Review by ukey54 — APPROVED** [review]
👍

**Comment by jr-sawaliram** [comment]
1. Translation credits are appearing on published answers but not on published articles.
2. While updating a submitted translation the credits addition does not work.
3. Credits terminology to be: Translator, Co-translator and Translation submitter.

**Comment by abhiprojectz** [comment]
Issues resolved.

**Comment by jr-sawaliram** [comment]
@ukey54 @Sshashank18 please test one more time.

**Pull request merged**
