### PR TITLE
Make admin fields optional

### LINKED ISSUE #173: Admin interface marks all fields as mandatory
Many of the fields (especially in the Question model) are allowed to be empty; however the Django Admin interface makes them mandatory in the edit form. This means you can't update a Question without filling all the fields, even if they were initially blank before you started editing.

### PR DESCRIPTION
**Pull request by badrihippo**
Fixes #173 and also adds new columns to the admin site's search display.

### CODE REVIEW

**Comment by badrihippo** [comment]
@dchandrika-tifr you'll be able to start making edits once this is merged in.

**Comment by nitinpaul** [comment]
@badrihippo wouldn't this require a migration file?

**Comment by badrihippo** [comment]
@nitinpaul it was working properly without, but here you go

**Comment by nitinpaul** [comment]
How will the changes be reflected in the database without running a migration? Is there some other configuration for this?

**Comment by badrihippo** [comment]
It seems like the database was anyway accepting blank fields by default. This just makes it explicit.

**Pull request merged**
