### PR TITLE
Translator notification review

### LINKED ISSUE #357: Translator does not get notification of Review
* Note - Translation review is part of Manage Content.
**For submitted translation**
* At present no notifications are being sent at the review stage of a translation.
* Notification of a review should be sent to the translator and any other reviewers.
* Translator’s response should trigger a notification to all the reviewers.
**For published translation**
* After publication the translator gets 2 notifications as below. Only the first of these is necessary.
WhatsApp Image 2021-05-25 at 3 48 00 PM
* The 2nd notification is also being sent to the publisher of the translation. This is not needed; it should be dropped.
* Notification text is incomplete. Notification title should fit in 50 characters. The 500 characters available for the description (currently unused) can have further info.
* Notification description should mention the initiator's name and **not** their email id.

### PR DESCRIPTION
**Pull request by Sshashank18**
This fixes #357

### CODE REVIEW

**Review by abhiprojectz — COMMENTED** [review]
:zap: **Checklist:**

:white_check_mark: Notifications are sent at the review stage of a translation
:white_check_mark: Not getting 2 notifications 
:white_check_mark: Shows Username instead of emailID
:white_check_mark: Notification text is complete

:?: `Notification of a review should be sent to the translator and any other reviewers.` i'm not sure what **any other reviewers**  actually means? if it means that another reviewer who adds his comment and some other published that content, then if the person who adds the comment should also get notification... then its not sending to that person.

**Comment by jr-sawaliram** [comment]
@abhiprojectz @Sshashank18 though not included in the issue description it does looks reasonable to send a notification to other reviewers after publication as well as after review. Multiple reviewed answers should be rare so such notifications would not be too many.

**Comment by jr-sawaliram** [comment]
```suggestions.csv``` should be deleted.

**Comment by Sshashank18** [comment]
1.Notification is already being sent to the other reviewers and translator after publication.
2. suggestions.csv deleted.

**Pull request closed without merging**
