### PR TITLE
Translation bug in article and answers is fixed

### PR DESCRIPTION
**Pull request by abhiprojectz**
This fixes issue [#360](https://github.com/sawaliram/sawaliram/issues/360)

**INFO:** For accurate results test this, after this  PR [#362](https://github.com/sawaliram/sawaliram/pull/362) is merged.

### CODE REVIEW

**Review by badrihippo — COMMENTED** [review]
Great! Are there any other places in `models.py` where `LANGUAGE_CHOICES` is being used instead of `CONTENT_LANGUAGES`? Even if they don't cause problems now they may make other bugs crop up in future

**Comment by abhiprojectz** [comment]
@badrihippo  No there is no more place , only `CONTENT_LANGUAGES` is being used.

**Comment by badrihippo** [comment]
Okay great! I think this will solve the issue then.

**Review by badrihippo — APPROVED** [review]

**Review by Sshashank18 — COMMENTED** [review]
working fine.

**Pull request merged**
