### PR TITLE
Question & Articles language changes

### PR DESCRIPTION
**Pull request by abhiprojectz**
Fixes [#379  ](https://github.com/sawaliram/sawaliram/issues/379)

### CODE REVIEW

**Review by ukey54 — APPROVED** [review]
Everything is working fine now 👍

**Review by badrihippo — CHANGES_REQUESTED** [review]
Code looks fine, but can you make the commit message a  bit more descriptive? (I mean the commit message, not the PR description). You can do that now by running `git commit --amend` followed by `git push --force` to get it up.

For what to write, you can copy from #379 and modify appropriately—even the full list is fine. The commit message should be something like "Display English version of titles during translation" (or @jr-sawaliram is there any more appropriate/concise way of saying it?) and after a blank line you can put the full description explaining what the commit does.

**Comment by abhiprojectz** [comment]
@badrihippo  Updated the commit msg as suggested by @jr-sawaliram

**Review by badrihippo — APPROVED** [review]
Looking good! @jr-sawaliram keep in mind next time that the commit message title can be a maximum of 70 characters (it got truncated here!). But I think this is good enough for now.

**Pull request merged**
