### PR TITLE
Add "published on" date field to relevant models

### LINKED ISSUE #241: Create a date stamp for "Published date" and "Submitted on (date)"
The system seems to have a "Created On" and records "Last updated" version but not when it was submitted and published. 

Can that information be explicitly visible? 
a) "Submitted on" (along with Submitted by) in Review Answers
b)  "Published on" (along with Approved by/Published by) in Submit answer page

This will help us also sort by "Submitted on" date. Right now, only way to locate a question is using Question ID. The date will help prioritize long pending submission (apart from sorting by just oldest-newest)

These changes could be best seen on the above pages and /admin/dashboard/answers.

### PR DESCRIPTION
**Pull request by badrihippo**
Implements a "published on" field to keep track of when an article was put out to the public (as opposed to created as a draft or updated.

Applies to the following models:
- [x] All draftables (articles, article translations, answer translations, etc)
- [x] Answers

Also displayed in the admin interface for:
- [x] Articles
- [x] Answers

Fixes #241.

### CODE REVIEW

**Comment by subindevs** [comment]
@badrihippo instead of having a "Published on " input for article, is it possible to get the published date and time automatically?

**Comment by badrihippo** [comment]
@subindevs it's not an input, just a database field. The `published_on` date and time will set automatically, the same way as `created_on` and `submitted_on`; this PR adds the appropriate fields in the database to store the information and to automatically set it when the item is published.

**Comment by subindevs** [comment]
@badrihippo 

screenshot
this articles have publish date even if its not published, and date and time is same as updated date and time

**Comment by subindevs** [comment]
@badrihippo 
It also created an input filed published on
sawaliramsecond

**Comment by badrihippo** [comment]
@subindevs this is expected behaviour: that way if the publish date is not set due to an omission in the view code it will at least display a usable value as a fallback. If you want to omit unpublished articles while searching, you can use the "status" filter without relying on publish date to indicate whether an item is published or not. (Similarly, the "updated on" field contains a value even when the item is newly created and has not yet been updated).

The "published on" date is editable in the admin interface. This is in order to make manual corrections if an error has occurred; in general all fields should be editable on the admin interface regardless of whether they are editable by ordinary users or not. @dchandrika-tifr and @jr-sawaliram please confirm.

**Comment by jr-sawaliram** [comment]
> The "published on" date is editable in the admin interface. This is in order to make manual corrections if an error has occurred; in general all fields should be editable on the admin interface regardless of whether they are editable by ordinary users or not. @dchandrika-tifr and @jr-sawaliram please confirm.

Confirmed!

**Comment by subindevs** [comment]
@badrihippo 
> @badrihippo
> 
> screenshot
> this articles have publish date even if its not published, and date and time is same as updated date and time

**Comment by badrihippo** [comment]
@subindevs
> @subindevs this is expected behaviour: that way if the publish date is not set due to an omission in the view code it will at least display a usable value as a fallback. If you want to omit unpublished articles while searching, you can use the "status" filter without relying on publish date to indicate whether an item is published or not. (Similarly, the "updated on" field contains a value even when the item is newly created and has not yet been updated).

**Review by subindevs — APPROVED** [review]

**Comment by jr-sawaliram** [comment]
@badrihippo now the date is visible at the admin interface for a newly published answer (no. 1078) but not for the older ones. Can this be fixed?

**Pull request merged**
