### PR TITLE
bootstrap updated to v4.4.1

### PR DESCRIPTION
**Pull request by abhiprojectz**
This PR updates bootstrap to v4.4.1
Fixes issue [#223](https://github.com/sawaliram/sawaliram/issues/223)

### CODE REVIEW

**Comment by Sshashank18** [comment]
I have checked the files and they are being updated to v4.4.1, but when i am checking the source files on website, i am getting the version as 4.1.1

**Comment by abhiprojectz** [comment]
> I have checked the files and they are being updated to v4.4.1, but when i am checking the source files on website, i am getting the version as 4.1.1

Did you run python manage.py collectstatic ? i think its not cached in your local staticfiles

**Comment by Sshashank18** [comment]
Yes i have run python manage.py collectstatic command also, but i am facing the same issue.

**Review by badrihippo — APPROVED** [review]

**Review by Sshashank18 — COMMENTED** [review]
Working fine for me

**Pull request merged**
