### PR TITLE
makes slug multilingual

### PR DESCRIPTION
**Pull request by abhiprojectz**
Fixes: [#419 ](https://github.com/sawaliram/sawaliram/issues/419)

**Makes slug function multilingual for articles**

### CODE REVIEW

**Review by badrihippo — CHANGES_REQUESTED** [review]
The logic is reversed. It should be `if slug: return slug; else return 'article'`. We want to return the string `article` only if a slug is not available.

(Right now, the function will return a blank string when the slug is empty and the string `article` for all other slugs; it will never return an actual slug).

**Comment by abhiprojectz** [comment]
The title in url is not correct , what should be done ? @badrihippo 

ytytytyt

**Comment by badrihippo** [comment]
@abhiprojectz that is how it's supposed to be (slugify removes all the spaces and commas etc. since those don't work as a URL but preserves the rest). Is the article loading properly without any errors? If so then this is fine.

**Comment by abhiprojectz** [comment]
@badrihippo  article is loading correctly , but the url text doesn't makes sense , what if we could add a field in articles model something like `slug` will be helpful in all other languages ? as we can put their the meaningful english slug .

**Comment by badrihippo** [comment]
The URL text doesn't have to make sense as a sentence; it just needs to have enough keywords so people can find it easily in their browser history, and to see what the article is going to be about before clicking. This "not making sense" happens even for English URLs:

> https://www.theguardian.com/food/2021/may/12/toast-haste-20-chefs-on-the-best-hot-sandwiches-to-make-in-a-hurry
> https://www.inc.com/jessica-stillman/introverts-public-speaking-charisma-reversals-keanu-reeves.html

Personally I think it's better to have the slug in the same language as the article itself, as long as the browser supports it (which will be taken care of by the `slugify` library). But if you still want English text maybe you can say that if there is an English translation available, it will slugify that, and fall back to Hindi only if an English translation is not available. Alternatively you can use the same strategy as questions which is to have a mandatory "English translation of article title" field.

**Comment by abhiprojectz** [comment]
@badrihippo  okay "The URL text doesn't have to make sense as a sentence" no issue if its the case.

**Comment by badrihippo** [comment]
Okay great. I think this is good then :slightly_smiling_face::+1:

**Review by badrihippo — APPROVED** [review]

**Comment by jr-sawaliram** [comment]
Merged. It works!  https://sawaliram.org/article/%E0%A4%B8%E0%A4%A7-%E0%A4%B8%E0%A4%B5%E0%A4%B2-%E0%A4%9F%E0%A4%A2-%E0%A4%9C%E0%A4%B5%E0%A4%AC-78?

**Pull request merged**
