### PR TITLE
Search Refactor

### LINKED ISSUE #253: Enable search by question ID
Useful for experts and reviewers and to facilitate dialogue among team members.

### PR DESCRIPTION
**Pull request by badrihippo**
Rework the search page to make it more intelligent and user-friendly
- [x] Implement support for multiple content types in search page, without assuming all results will be questions
  - [x] Update code to make appropriate queries depending on which content-types are selected*
  - [x] Select all content-types by default on blank search page*
  - [x] Disable question-specific filters when "questions" filter is not selected*
- [x] Update child views to work with the refactored `SearchView`*
- [x] Display articles as well as answers in "Translate Content" page*
- [x] Enable FTS (full-text search) 
- [x] Set translation strings in search page template*
- [x] Style search pages to look better on mobile
  - [x] Activate filters on mobile
  - [x] Activate "sorting" option on mobile
  - [x] Add margins to make things look neater
- [x] Make filters apply to articles (and hide them if irrelevant filters are applied)
- [x] Allow searching by question ID (fixes #253)
- [x] Allow searching by article ID

### CODE REVIEW

**Comment by nitinpaul** [comment]
@badrihippo so I noticed a few issues, might be possible they are happening because of merge issues:
1. Selecting 'Articles' doesn't hide the questions, it shows both questions and articles.
2. Selecting 'Answered' breaks the page with the error "name 'result' is not defined'"
3. Searching for something breaks the page with "invalid literal for int() with base 10: 'earth'"
4. The results counter at the top is malfunctioning - it shows "Showing - of 2023 results"
5. Picking a language (/search?q=&language=te) shows the English articles too, in addition to the Telugu questions. 
6. Articles are almost always displayed, eg. when selecting curriculum (/search?q=&category=questions&curriculum=CBSE)

There are other smaller issues - but I would suggest merging this branch with the current master and then pushing that branch. I might be merging stuff incorrectly, especially the search template!

**Comment by badrihippo** [comment]
Okay, so I've fixed 1-3.
4. is a major operation so let's leave till later (it's the one @tannucheria was working on)
5 and 6. are because none of the other article filters apply to questions. I'm not sure what should be the default behaviour for this: should it show no articles at all, if any of the questions filters are selected? For now, I've made the search select questions only by default so people can select articles etc. later if they want them, but that's not an ideal final solution.

**Comment by nitinpaul** [comment]
Why is 4 a major operation? Shouldn't it just display the start and ending indexes of the first page of results?
For 5 & 6 - Language is not a Question filter exclusively, it will, of course, apply to Articles, since Articles can be translated too. If an article is not available in a language, it should be hidden. If any of the Questions only filter is applied, like Curriculum, then the Articles should be hidden.

**Comment by jr-sawaliram** [comment]
@badrihippo, @nitinpaul please update me on the status of this PR. Thanks.

**Comment by badrihippo** [comment]
@jr-sawaliram I had paused work on this to finalise the translations PR. Moving back to this now; it should be done by next week.

@nitinpaul ok, got it. 5 & 6 fixes coming up.

4 isn't a major operation by itself, but we need to set up pagination for it to work properly. Right now, the search page shows *all* articles on page 1, and then paginates the questions (so if pages have 10 questions each, the first page will have 10+n questions for n article results).

What we need to do is write a custom pagination which

* displays upto 10 (or whatever the setting is) articles per page, slicing properly depending on which page of the search results we're in
* if there are (a < 10) articles, then display all remaining articles plus (10-a) answers
* display only answers on subsequent pages, starting the count from where we left off in the "articles + answers" page
* (also repeat for other content-types that we add in future).

I have a vague idea of how to do this, but I think it's better to do it as a separate PR so it doesn't cause too much confusion. I'll do it once the more urgent bugs are fixed.

**Comment by badrihippo** [comment]
@nitinpaul ready for review

**Comment by nitinpaul** [comment]
I think it's best to not have this kind of logic for the pagination. Simply combine all the results into one object that has all the content - articles,answers, resources etc and paginate it. The order in which content should appear shouldn't affect the pagination. 

If there is a search term, the results appear in order of relevance to the search. If filters and sort are there, then the results are ordered as per them. 

We can just decide to list the articles first, or something else first in case of an empty search. In any case, displaying 10 articles in one page and all need not be there.

**Comment by badrihippo** [comment]
I can do that, but how would it work on the database end? I don't know of any way to combine multiple content types (eg. both Questions and Articles) into one QuerySet. That means I'd have to pull *all* objects from the database each time put them into a Python list, and then paginate that list. Just wondering if it'd cause any performance issues...🤔

**Comment by nitinpaul** [comment]
Not all the objects but even now we run multiple queries for different content types. I don't think we can get around that. Combining the QuerySets into one shouldn't be a performance drain.

**Comment by jr-sawaliram** [comment]
> We can just decide to list the articles first, or something else first in case of an empty search.
There seems to be a basic issue with having different content types listed on one page and leaving the filtering to be done by the user. I will continue the thread on [Zulip](https://sawaliram.zulipchat.com/#narrow/stream/198795-dev.2F/topic/search).

**Comment by badrihippo** [comment]
> Not all the objects but even now we run multiple queries for different content types. I don't think we can get around that. Combining the QuerySets into one shouldn't be a performance drain.

But how do I know how many objects of each type to retrieve in the query? Or should I just pull the top 15 for each type?

I can't simply add QuerySets (`Question.objects.all() + Answer.objects.all()` is invalid), so the way I understand, it would have be something like:

```py3
all_results = []
n = 15 # or what should this be?

for r in Question.objects.filter(...).limit(n):
    all_results.append(r)

for r in Article.objects.filter(...).limit(n):
    all_results.append(r)

for r in Resources .objects.filter(...).limit(n): # whenever this happens
    all_results.append(r)

paginator = Paginator(all_results, 15)
```

The other option is to run the above without `.limit()`, but would cause a performance drain since we're not lazy-loading results any more (they're all being loaded into the list). Of course if the numbers are small then that may not be an issue either—do you think I should just try it, and we can fix it later if it gets too slow?

**Comment by badrihippo** [comment]
Just found [this answer](https://stackoverflow.com/a/434755/1196444)—might be a solution to our problem. Let me check.

**Comment by badrihippo** [comment]
[This Django snippet](http://www.djangosnippets.org/snippets/1933/) seems to support what we're trying to do (it's similar to the custom pagination I wanted to write, but packaged as a class). It's also been bundled into [a package](https://github.com/percipient/django-querysetsequence). I think I'd better do it as a separate PR though.

The other option is to use the `QuerySet.union()` method, but that only works if we use `.values()` to pick an exact number of fields each time.

**Comment by nitinpaul** [comment]
`itertools` look promising. Maybe give it a shot? Best not to use a package for a functionality that can be built in-house. It will help us be a bit more lean with dependencies. 
Why to use `n=15` or some arbitrary limit? We can't limit the query for the sorting functionality to work correctly.
We can maybe look into caching the empty search page results since that will be same most of the time. What do you think?

**Comment by badrihippo** [comment]
Okay, if loading the whole QuerySet into Python is not a concern we can skip the `n=15`. Maybe we can trim down the data size some other way, like specifying only some fields to select (eg. not the whole answer or article content)?

I'll give `itertools` a shot when I have some time this weekend. It's anyway the same as the library, as far as I can make out (the latter has some more features, but we don't necessarily need those). And yeah, caching the empty search page would be a good idea; it'll cut down the load dramatically.

**Comment by jr-sawaliram** [comment]
@nitinpaul, @badrihippo what is the update here?

**Pull request merged**
