### PR TITLE
Signup for developers

### LINKED ISSUE #338: Sign up for developers
Sign up in the local server should not require email verification.  

Add a line to the signup code to set email_verified to true if the environment is a development environment.

### PR DESCRIPTION
**Pull request by Sshashank18**
This closes #338

### CODE REVIEW

**Comment by subindevs** [comment]
@Sshashank18 apart from disabling email versification for developers, what are the other changes included in this PR?

**Comment by Sshashank18** [comment]
This PR only include disabling email verification for developers.
But i don't know why all my commits are being displayed

**Review by subindevs — CHANGES_REQUESTED** [review]
signup was successful,  but can't sign in , showing connection refused error

**Review by subindevs — APPROVED** [review]

**Comment by Sshashank18** [comment]
@abhiprojectz it is showing that error because you will be trying to run localhost:8000/users/signup instead of 127.0.0.1:8000/users/signup. And recaptcha only support 127.0.0.1:8000 as localhost url

**Comment by abhiprojectz** [comment]
Do we have to generate the site key for testing and then pass it in env?  
and also i think solving recaptcha  in local testing is not handy/quick.

**Comment by Sshashank18** [comment]
Yes, site key has to be generated for testing.
Okk i will remove it from localhost
Seems like a fair point.

**Pull request merged**
