### PR TITLE
Implement "Review Answers" view

### PR DESCRIPTION
**Pull request by badrihippo**
First draft of the "review answer" page. I added multiple commits to make it easier to inspect/cherry-pick changes.

Some points:

* Is the author name (person who answered the question) meant to be visible during review? :bust_in_silhouette:
* I couldn't figure out what the URL scheme is so made up my own...you might want to change it :stuck_out_tongue:
* I updated the QuillJS theme so that the text has the same style during viewing vs. editing :memo:
* The "list of unreviewed answers" page highlights the question title, rather than the answer text. It may make more sense to highlight the answer text; we should check which design works better :art:

I also notice the field-cleaning and permissions checks haven't been very stringently implemented—I'm assuming that's left for a future overhaul sometime?

### CODE REVIEW

**Comment by nitinpaul** [comment]
Few quick questions before I test:
1. What is the purpose of `accept_question()` in `QuestionArchive`? 
2. Is the `quill.sawaliram.css` file an edited version of the quillJS CSS file? Or is it simply an offline copy of the CSS file which was being served by CDN

**Comment by badrihippo** [comment]
1. `accept_question()` is a helper function to convert a `QuestionArchive` to a `Question`. The initial reason was because importing the Excel Sheet makes `QuestionArchive`s; I needed a quick way to convert them to `Question`s for testing.  
I committed it since it may be useful in the future, with modifications, while implementing the "Accept Question" view. If not you can just drop that one while merging.

2. `quill.sawaliram.css` is lightly edited. I basically changed the text formatting so it uses the same font as while viewing the final answer (Sawaliram default font rather than the QuillJS custom font)

**Comment by nitinpaul** [comment]
A few more points:
1. `accept_question()` seems handy. When adding utility code like this one, always always add a comment clearly stating it's intent and an example of how to use it. Remember, if you want other devs to use your code, you need to add documentation.
2. It's a good practice to keep the files from any library/tool untouched, especially stylesheets. The devs behind quill.js might have tested this code across browsers, and might have optimised it. We could be introducing new bugs into the codebase by directly editing the file. A good approach would be to override the styles from our own stylesheet. Also, if the original file remains untouched, we can easily remove our overrides and fallback to the default styles in case there is an issue. 
3. The current URL structure of the project could be way better, we should discuss and improve this. The scheme you used works, so we'll keep it for now and improve the whole structure before rollout. 
4. The review answer page does not have a button to approve the answer, which is the main task of the page.
5. The comment field need not have a rich-text editor. A simple TextField will do.

These are quick fixes. Hope you can take a look at them over the weekend!

**Comment by badrihippo** [comment]
OK, thanks for the feedback. I'll add the comment, and change the stylesheet and editor as per your points (1), (2) and (5).

The review answer button is present only if you're not the author of the answer (users can't approve their own answers). You should see if if you sign in as a different user; I'll confirm this and get back.

I guess we can discuss the URL structure separately. Should we start a new issue?

**Comment by nitinpaul** [comment]
We'll keep the URL issue on hold for now, we need a plan for the next phase of development first.
You missed point (5), the comment field is still the rich text editor.

**Comment by badrihippo** [comment]
Oops, yeah, I forgot about (5). I'll submit by this weekend.

**Comment by nitinpaul** [comment]
Looking at the JS code, it is a bit confusing. I'll lay out the points below:
1. The JS code should go in the `script.js` file, which is linked in the base template and is loaded automatically. 
2. We're using JQuery, which makes writing JS a lot more enjoyable. Something to look into.

The JS code here is a bit difficult to follow, and you certainly do not need to create HTML elements in JS. How about this alternate approach:
* Every comment will have an HTML structure similar to something like this for the delete action - 
```html
<button class='delete-comment' data-comment-id='{{ comment.id }}'>Delete</button>
<span class='delete-comment-prompt'>
  Do you really want to delete this comment?
  <form action='<url>' method='POST'>
    <input type='hidden' name='comment-id' value='{{ comment.id }}'>
    <button class='confirm-delete-comment' data-comment-id='{{ comment.id }}'>Yes</button>
  </form>
  <button class='cancel-delete-comment'>No</button>
</span>
```
The `delete-comment-prompt` class has the style `display: none`, which keeps the spans hidden on page load.
* When a user clicks the delete button, it should display the span right after the button that is clicked (which has the prompt). In JQuery, it can be written as follows:
```javascript
$('.delete-comment').click(function() {
  $('.delete-comment-prompt').next().show(); // show the next element with class 'delete-comment-prompt'
});
```
* If the user clicks yes, then it submits the form with the comment ID, the comment gets deleted from the database and the page gets reloaded with the comment now deleted.
* If the user clicks no (button element with class `cancel-delete-comment`), then we basically want to hide the `span`. The `span` is the parent of this button, therefore we can simply hide the parent like so: 
```javascript
$('.cancel-delete-comment').click(function() {
  $(this).parent('span').hide();  // hide the parent which is a span
});
```
And we also show the corresponding delete button for this particular comment. 

Another approach would be to have a `data-comment-id` on every element and select each span or button by class and by attribute, so we always perform some action on specifically the element with say, class `delete-comment-prompt` and `data-comment-id` attribute equal to 5. 

The whole JS can be written more simply and in 10 lines max if we use JQuery and this approach. As always, feel free to ask any questions :)

**Comment by badrihippo** [comment]
Thanks! I didn't realise we had jQuery (newer websites had stopped using it of late).

And yes, your method makes more sense now that I think about it. I was wondering about the trade-off between having multiple redundant `<span>`s which probably wouldn't be used, but I suppose it's not much in this case (especially given that most people won't comment more than a few times).

Looking at the docs now to refresh my memory. Commits by this evening hopefully.

**Comment by nitinpaul** [comment]
Hey Badri, thanks for another quick submission! The code works as intended, there are only small fixes to do, and some clarifications:
1. I'm not aware if newer websites stopped using JQuery, but Bootstrap requires JQuery, so we have it.
2. What does this construct do? `$(()=>{};` on line 109 in `script.js`
3. You might want to add this code in a function like `setupCommentDeletion()` in `script.js`. This code is intended for only a few pages, so it need not be needlessly loaded on every page. Once we decide on the URL structure, we'll call every function in the JS  file only for the relevant page, like `setupQuillEditor()` on line 99.
4. What is the purpose of `html('delete?')` on line 111 in `script.js`?
5. Why is the `method` attribute of `form.comment-delete-form` element being switched between `GET` and `POST`?

**Comment by badrihippo** [comment]
1. Oh yeah, Bootstrap does use jQuery. Might as well use it since it's there, then 😉
2. It's shorthand for `$(document).ready(function(){...});` to run a function only after the whole page has finished loading. But I guess this goes because of point 3
3. Good idea, I'll do that. To make things even more organised, perhaps we should run the functions on the page itself, rather than let the script decide? (Maybe topic for a separate issue)
4. `.html('delete?')` is part of the graceful fallback. By default, the button will say "delete" and load the delete confirm page when clicked. If JavaScript is enabled, it'll change to "delete?" with a question-mark and do the confirmation dynamically without having to load a separate page.
5. This is again part of the graceful fallback. If JS doesn't work, it'll go to the confirm page rather than deleting without confirmation. (I guess I don't have to keep toggling back and forth though: once should be enough 😛).

**Comment by nitinpaul** [comment]
As a rule of thumb, the ready function is intended to run some JS as soon as the page is loaded. In our case, we only want to perform an action once the user clicks on a particular element. I think this code will work fine without the ready function.

As for Javascript being disabled, the percentage is too low ([less than 2%](https://www.mediawiki.org/wiki/No-JavaScript_notes)) to write fallbacks for. Let's not worry about that. As far as I'm concerned, if you're disabling something that is required for the website to function properly, then you're accepting a less than ideal user experience for yourself. I think we can remove the fallbacks for now!

**Comment by badrihippo** [comment]
The function in question sets the handlers (`onclick`) for the `<button>`s, so it does have to be called only after they're loaded. Hence the `ready` function.

It's not only about people disabling JS. In my case, for example, the Internet is bad so JS sometimes fails to load, which means I rely on the fallback to get things done—and if websites don't offer that there's s tendency not to use it so often. I don't know how Sawaliram end users are going to operate, but I'm pretty sure there'll be times they operate off a shaky connection (especially given we support mobile).

More commonly, there's the risk of users clicking "delete" before the page had fully loaded (meaning JavaScript not yet activated), and end up deleting data without confirmation. I think it's important to have a fallback for these edge cases, especially when it involves permanent changes like deleting data.

(I'm planning to remove the form toggling though: that certainly is unnecessary)

**Comment by nitinpaul** [comment]
Browsers parse HTML documents in a top-down manner. Given that all our JS files are at the bottom of the page, I can't think of a scenario where the scripts are loaded before these elements. If you think about it, shouldn't all our JS code be inside the `ready()` function if we follow this principle?

As for the JS files not loading due to a shaky internet connection, one important thing to remember is caching. The JS files, images, font files and a few other assets will be cached by the browser and need not be downloaded every time the page is loaded. Even if we decide to write fallbacks just to be safe owing to this reason, we might have to write fallbacks for all the Bootstrap functionality we're using, the quill editor and all of our custom JS, which is not practical at all. 

If the JS doesn't load properly, clicking the delete button should not do anything, should it?

**Comment by nitinpaul** [comment]
One point that I missed - I think we agreed that we don't need `quill.sawaliram.css` file. You can move those styles to `style.css`. Having the CSS in one place is better.

**Comment by badrihippo** [comment]
**ready() function:** I see your point. I'd assumed there were times JS executed early, or why else would the have  a `ready()` function in the first place? But I realise now that it's for external scripts and libraries which are not guaranteed to be loaded at the end.

(Side note: would it make sense to keep it encapsulated, just in case the script is imported early by somebody for some reason?)

**quill.sawaliram.css:** As of 246d912964432a5527cdc4700bc264568b8fc57e, the file only holds changes that override (customise) the stock quill file. The rest is inherited from the stock code. I thought it'd be neater to keep it in the separate file, but I could also move it to `style.css`. Which do you prefer?

**graceful degradation** (that's the technical term, apparently): Theoretically, caching would help, but it doesn't always work in practice. It also doesn't account for first load, when scripts wouldn't have been cached yet. In my experience, there are lots of ways scripts can fail to load and it helps a lot when there's a fallback in place.

On the practical side, Bootstrap seems to degrade gracefully in most cases. QuillJS doesn't but I could set it up. We don't have to do it for more advanced functions, but I still think we should support the basics. (As it stands now, the button defaults to submitting to the "confirm deletion" page, unless JS loads).

Maybe we should move this to a separate issue or chat though? It seems a broader issue than the scope of this commit!

**Comment by nitinpaul** [comment]
Hey Badri, why are there edits on so many files? And about 80 commits? I think some git flow was broken

**Comment by badrihippo** [comment]
@nitinpaul most of those commits are from `master`. I usually don't like doing this, but this was the only way to make sure the code was working after all the refactoring. They'll disappear when you merge it back into `master` (either right now, or when I've done the other tweaks).

**Comment by nitinpaul** [comment]
I don't quite follow, what do you mean they are from `master`? Didn't you checkout a branch from `master` before starting with the work? Or is it still the old branch from April?

**Comment by badrihippo** [comment]
It's the old branch from April

**Pull request merged**
